
{DEFAULT @TARGET_CDMV5_SCHEMA = '' } -- the target CDMv5 database plus schema
{DEFAULT @CONDITION_ERA_TABLE_NAME = 'condition_era' } 
{DEFAULT @DRUG_ERA_TABLE_NAME = 'drug_era' } 



IF OBJECT_ID('@TARGET_CDMV5_SCHEMA.@CONDITION_ERA_TABLE_NAME', 'U') IS NOT NULL
	BEGIN 
			IF OBJECT_ID('@TARGET_CDMV5_SCHEMA.@DRUG_ERA_TABLE_NAME', 'U') IS NOT NULL
				BEGIN 
					SELECT 1
				END
			ELSE 
				BEGIN 
					SELECT 0
				END
			;
	END
ELSE 
	BEGIN 
		SELECT 0
	END
;
